POST http://localhost:3000/api/visitas
Content-Type: application/json

{
    "titulo": "Visita na Delta Horario TESTAR 2",
    "horaInicio": "2022-02-20T09:00:10",
    "horaFinal": "2022-02-20T13:25:17",
    "descricao": "Qualquer descricao de delta com horas",
    "escritorio": true,
    "dataVisita": "2022-03-27T09:00:10"
}

###
GET http://localhost:3000/api/visitas

###
GET http://localhost:3000/api/visitas/63ac8ea93349248503a328e1

###
PUT  http://localhost:3000/api/visitas/63ac6c509403b13ca556d480
Content-Type: application/json

{
    "titulo": "Visita na Delta Alterada",
    "descricao": "Qualquer descricao de delta alterada",
    "horaInicio": "18:15",
    "horaFinal": "22:30",
    "escritorio": false
}

###
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dataInicial": "2022-03-18T09:00:10",
    "dataFinal": "2022-03-23T13:25:17",
    "valorHora": 300
} 

###
GET http://localhost:3000/api/consultas/63ade0595aaa62764a55bed6

       
