POST http://localhost:3000/api/visitas
Content-Type: application/json

{
    "titulo": "Visita na Delta Horario testado 2",
    "horaInicio": "2022-02-20T09:00:10",
    "horaFinal": "2022-02-20T13:25:17",
    "descricao": "Qualquer descricao de delta com horas",
    "escritorio": true
}

###
GET http://localhost:3000/api/visitas

###
GET http://localhost:3000/api/visitas/63ac8ea93349248503a328e1

###
PUT  http://localhost:3000/api/visitas/63ac6c509403b13ca556d480
Content-Type: application/json

{
    "titulo": "Visita na Delta Alterada",
    "descricao": "Qualquer descricao de delta alterada",
    "horaInicio": "18:15",
    "horaFinal": "22:30",
    "escritorio": false
}

###
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dataInicial": "2022-02-20T09:00:10",
    "dataFinal": "2022-02-20T13:25:17",
    "valorHora": 300,
    "visitas": [
        {
            "titulo": "Visita na Delta Alterada",
            "descricao": "Qualquer descricao de delta alterada",
            "horaInicio": "2022-02-20T12:00:10.000Z",
            "horaFinal": "2022-02-20T16:25:17.000Z",
            "escritorio": false,
            "almoco": false
        },
        {
            "titulo": "Visita na Delta Horario testado 2",
            "descricao": "Qualquer descricao de delta com horas",
            "horaInicio": "2022-02-20T12:00:10.000Z",
            "horaFinal": "2022-02-20T16:25:17.000Z",
            "escritorio": true,
            "almoco": false
        },
        {
            "titulo": "Visita na Delta Horario testado",
            "descricao": "Qualquer descricao de delta com horas",
            "horaInicio": "2022-02-20T12:00:10.000Z",
            "horaFinal": "2022-02-20T16:25:17.000Z",
            "escritorio": true,
            "almoco": false
        }
    ]
}
